spring.application.name=Starter
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d8leglu47okc738a108g-a.oregon-postgres.render.com:5432/test_deploy_3kpa
spring.datasource.username=test_deploy_3kpa_user
spring.datasource.password=vrlbMPfN324iKXPmbMVrAaWMinA7whZ7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=john
spring.security.user.password=john